module performance
{
struct Performance
{
     long m1;
     long m2;
     long m3;
     long m4;
     long m5;
     long m6;
     long m7;
     long m8;
     long m9;
     long m10;
     long m11;
     long m12;
     long m13;
     long m14;
     long m15;
     long m16;
     long m17;
     long m18;
     long m19;
     long m20;
     long m21;
     long m22;
     long m23;
     long m24;
     long m25;
     long m26;
     long m27;
     long m28;
     long m29;
     long m30;
     long m31;
     long m32;
     long m33;
     long m34;
     long m35;
     long m36;
     long m37;
     long m38;
     long m39;
     long m40;
     long m41;
     long m42;
     long m43;
     long m44;
     long m45;
     long m46;
     long m47;
     long m48;
     long m49;
     long m50;
     long m51;
     long m52;
     long m53;
     long m54;
     long m55;
     long m56;
     long m57;
     long m58;
     long m59;
     long m60;
     long m61;
     long m62;
     long m63;
     long m64;
     long m65;
     long m66;
     long m67;
     long m68;
     long m69;
     long m70;
};

};
