/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * FAST_BUFFERS_LICENSE file included in this Fast Buffers distribution.
 *
 *************************************************************************
 * 
 * @file EnumerationsExample.cpp
 * This source file contains an example of serialization/deserialization using one data type in the IDL file.
 *
 * This file was generated by the tool fastbuffers.
 */

#include "Enumerations.h"
#include "fastcdr/FastCdr.h"

#include "fastcdr/exceptions/Exception.h"

#ifdef __linux
#include <unistd.h>
#endif

#include <malloc.h>
#include <iostream>

using namespace eprosima::fastcdr;

bool FBug96Test()
{
    Bug96Test::simpleStruct_6 si;

    si.en(Bug96Test::GREEN);

    // Create the serializer object.
    char *buffer = (char*)calloc(1, si.getMaxCdrSerializedSize());
    FastBuffer fbuffer(buffer, si.getMaxCdrSerializedSize());
    FastCdr serializer(fbuffer);

    // Serialize structure.
    try
    {
        serializer << si;
    }
    catch(eprosima::fastcdr::exception::Exception &ex)
    {
        std::cout << "TEST FAILED<FBug96Test>: Serialization. " << ex.what() << std::endl;
        free(buffer);
        return false;
    }

    // Reset serializer object.
    serializer.reset();

    // Object used to deserialize the data.
    Bug96Test::simpleStruct_6 sires;

    // Deserialize structure.
    try
    {
        serializer >> sires;
    }
    catch(eprosima::fastcdr::exception::Exception &ex)
    {
        std::cout << "TEST FAILED<FBug95Test>: Deserialization. " << ex.what() << std::endl;
        free(buffer);
        return false;
    }

    // Compare data.
    bool compareOK = true;

    compareOK &= si.en() == sires.en();

    if(!compareOK)
    {
        std::cout << "TEST FAILED<FBug96Test>: Wrong values" << std::endl;
        free(buffer);
        return false;
    }

    return true;
}

int main()
{
    bool results = true;

    results &= FBug96Test();

    if(!results)
    {
        std::cout << "TEST FAILED" << std::endl;
        _exit(-1);
    }

    std::cout << "TEST SUCCESSFULLY" << std::endl;

    _exit(0);
    return 0;
}
