/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * FAST_BUFFERS_LICENSE file included in this Fast Buffers distribution.
 *
 *************************************************************************
 * 
 * @file HelloWorldExample.cpp
 * This source file contains an example of serialization/deserialization using one data type in the IDL file.
 *
 * This file was generated by the tool fastbuffers.
 */

#include "HelloWorld.h"
#include "fastcdr/Cdr.h"

#include "fastcdr/exceptions/Exception.h"

#include <iostream>

using namespace eprosima::fastcdr;

int main()
{
    FastBuffer fastbuffer;
    Cdr hellocdr_ser(fastbuffer);

    // Structure to serialize.
    HelloWorld hello_ser;
    hello_ser.message("Hello World");

    // Serialization.
    hellocdr_ser << hello_ser;
    
    // Reset the reading position in the serializer object to start deserialization.
    hellocdr_ser.reset();
    
    // The buffer will be deserialized in the next structure.
    HelloWorld hello_des;
    
    // Deserialization.
    hellocdr_ser >> hello_des;
    
    std::cout << hello_des.message() << std::endl;

    return 0;
}


