// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Performance_40.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Performance_40.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace performance {

namespace {

const ::google::protobuf::Descriptor* Performance_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Performance_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_Performance_5f40_2eproto() {
  protobuf_AddDesc_Performance_5f40_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Performance_40.proto");
  GOOGLE_CHECK(file != NULL);
  Performance_descriptor_ = file->message_type(0);
  static const int Performance_offsets_[40] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m3_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m4_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m5_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m6_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m7_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m8_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m9_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m10_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m11_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m12_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m13_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m14_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m15_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m16_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m17_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m18_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m19_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m20_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m21_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m22_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m23_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m24_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m25_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m26_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m27_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m28_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m29_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m30_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m31_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m32_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m33_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m34_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m35_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m36_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m37_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m38_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m39_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, m40_),
  };
  Performance_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Performance_descriptor_,
      Performance::default_instance_,
      Performance_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Performance, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Performance));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Performance_5f40_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Performance_descriptor_, &Performance::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Performance_5f40_2eproto() {
  delete Performance::default_instance_;
  delete Performance_reflection_;
}

void protobuf_AddDesc_Performance_5f40_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024Performance_40.proto\022\013performance\"\214\004\n\013"
    "Performance\022\n\n\002m1\030\001 \002(\017\022\n\n\002m2\030\002 \002(\017\022\n\n\002m"
    "3\030\003 \002(\017\022\n\n\002m4\030\004 \002(\017\022\n\n\002m5\030\005 \002(\017\022\n\n\002m6\030\006 "
    "\002(\017\022\n\n\002m7\030\007 \002(\017\022\n\n\002m8\030\010 \002(\017\022\n\n\002m9\030\t \002(\017\022"
    "\013\n\003m10\030\n \002(\017\022\013\n\003m11\030\013 \002(\017\022\013\n\003m12\030\014 \002(\017\022\013"
    "\n\003m13\030\r \002(\017\022\013\n\003m14\030\016 \002(\017\022\013\n\003m15\030\017 \002(\017\022\013\n"
    "\003m16\030\020 \002(\017\022\013\n\003m17\030\021 \002(\017\022\013\n\003m18\030\022 \002(\017\022\013\n\003"
    "m19\030\023 \002(\017\022\013\n\003m20\030\024 \002(\017\022\013\n\003m21\030\025 \002(\017\022\013\n\003m"
    "22\030\026 \002(\017\022\013\n\003m23\030\027 \002(\017\022\013\n\003m24\030\030 \002(\017\022\013\n\003m2"
    "5\030\031 \002(\017\022\013\n\003m26\030\032 \002(\017\022\013\n\003m27\030\033 \002(\017\022\013\n\003m28"
    "\030\034 \002(\017\022\013\n\003m29\030\035 \002(\017\022\013\n\003m30\030\036 \002(\017\022\013\n\003m31\030"
    "\037 \002(\017\022\013\n\003m32\030  \002(\017\022\013\n\003m33\030! \002(\017\022\013\n\003m34\030\""
    " \002(\017\022\013\n\003m35\030# \002(\017\022\013\n\003m36\030$ \002(\017\022\013\n\003m37\030% "
    "\002(\017\022\013\n\003m38\030& \002(\017\022\013\n\003m39\030\' \002(\017\022\013\n\003m40\030( \002"
    "(\017", 562);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Performance_40.proto", &protobuf_RegisterTypes);
  Performance::default_instance_ = new Performance();
  Performance::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Performance_5f40_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Performance_5f40_2eproto {
  StaticDescriptorInitializer_Performance_5f40_2eproto() {
    protobuf_AddDesc_Performance_5f40_2eproto();
  }
} static_descriptor_initializer_Performance_5f40_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Performance::kM1FieldNumber;
const int Performance::kM2FieldNumber;
const int Performance::kM3FieldNumber;
const int Performance::kM4FieldNumber;
const int Performance::kM5FieldNumber;
const int Performance::kM6FieldNumber;
const int Performance::kM7FieldNumber;
const int Performance::kM8FieldNumber;
const int Performance::kM9FieldNumber;
const int Performance::kM10FieldNumber;
const int Performance::kM11FieldNumber;
const int Performance::kM12FieldNumber;
const int Performance::kM13FieldNumber;
const int Performance::kM14FieldNumber;
const int Performance::kM15FieldNumber;
const int Performance::kM16FieldNumber;
const int Performance::kM17FieldNumber;
const int Performance::kM18FieldNumber;
const int Performance::kM19FieldNumber;
const int Performance::kM20FieldNumber;
const int Performance::kM21FieldNumber;
const int Performance::kM22FieldNumber;
const int Performance::kM23FieldNumber;
const int Performance::kM24FieldNumber;
const int Performance::kM25FieldNumber;
const int Performance::kM26FieldNumber;
const int Performance::kM27FieldNumber;
const int Performance::kM28FieldNumber;
const int Performance::kM29FieldNumber;
const int Performance::kM30FieldNumber;
const int Performance::kM31FieldNumber;
const int Performance::kM32FieldNumber;
const int Performance::kM33FieldNumber;
const int Performance::kM34FieldNumber;
const int Performance::kM35FieldNumber;
const int Performance::kM36FieldNumber;
const int Performance::kM37FieldNumber;
const int Performance::kM38FieldNumber;
const int Performance::kM39FieldNumber;
const int Performance::kM40FieldNumber;
#endif  // !_MSC_VER

Performance::Performance()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Performance::InitAsDefaultInstance() {
}

Performance::Performance(const Performance& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Performance::SharedCtor() {
  _cached_size_ = 0;
  m1_ = 0;
  m2_ = 0;
  m3_ = 0;
  m4_ = 0;
  m5_ = 0;
  m6_ = 0;
  m7_ = 0;
  m8_ = 0;
  m9_ = 0;
  m10_ = 0;
  m11_ = 0;
  m12_ = 0;
  m13_ = 0;
  m14_ = 0;
  m15_ = 0;
  m16_ = 0;
  m17_ = 0;
  m18_ = 0;
  m19_ = 0;
  m20_ = 0;
  m21_ = 0;
  m22_ = 0;
  m23_ = 0;
  m24_ = 0;
  m25_ = 0;
  m26_ = 0;
  m27_ = 0;
  m28_ = 0;
  m29_ = 0;
  m30_ = 0;
  m31_ = 0;
  m32_ = 0;
  m33_ = 0;
  m34_ = 0;
  m35_ = 0;
  m36_ = 0;
  m37_ = 0;
  m38_ = 0;
  m39_ = 0;
  m40_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Performance::~Performance() {
  SharedDtor();
}

void Performance::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Performance::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Performance::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Performance_descriptor_;
}

const Performance& Performance::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_Performance_5f40_2eproto();
  return *default_instance_;
}

Performance* Performance::default_instance_ = NULL;

Performance* Performance::New() const {
  return new Performance;
}

void Performance::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    m1_ = 0;
    m2_ = 0;
    m3_ = 0;
    m4_ = 0;
    m5_ = 0;
    m6_ = 0;
    m7_ = 0;
    m8_ = 0;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    m9_ = 0;
    m10_ = 0;
    m11_ = 0;
    m12_ = 0;
    m13_ = 0;
    m14_ = 0;
    m15_ = 0;
    m16_ = 0;
  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    m17_ = 0;
    m18_ = 0;
    m19_ = 0;
    m20_ = 0;
    m21_ = 0;
    m22_ = 0;
    m23_ = 0;
    m24_ = 0;
  }
  if (_has_bits_[24 / 32] & (0xffu << (24 % 32))) {
    m25_ = 0;
    m26_ = 0;
    m27_ = 0;
    m28_ = 0;
    m29_ = 0;
    m30_ = 0;
    m31_ = 0;
    m32_ = 0;
  }
  if (_has_bits_[32 / 32] & (0xffu << (32 % 32))) {
    m33_ = 0;
    m34_ = 0;
    m35_ = 0;
    m36_ = 0;
    m37_ = 0;
    m38_ = 0;
    m39_ = 0;
    m40_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Performance::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required sfixed32 m1 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m1_)));
          set_has_m1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(21)) goto parse_m2;
        break;
      }

      // required sfixed32 m2 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m2_)));
          set_has_m2();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(29)) goto parse_m3;
        break;
      }

      // required sfixed32 m3 = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m3_)));
          set_has_m3();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(37)) goto parse_m4;
        break;
      }

      // required sfixed32 m4 = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m4_)));
          set_has_m4();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(45)) goto parse_m5;
        break;
      }

      // required sfixed32 m5 = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m5_)));
          set_has_m5();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(53)) goto parse_m6;
        break;
      }

      // required sfixed32 m6 = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m6:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m6_)));
          set_has_m6();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(61)) goto parse_m7;
        break;
      }

      // required sfixed32 m7 = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m7:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m7_)));
          set_has_m7();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(69)) goto parse_m8;
        break;
      }

      // required sfixed32 m8 = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m8:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m8_)));
          set_has_m8();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(77)) goto parse_m9;
        break;
      }

      // required sfixed32 m9 = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m9:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m9_)));
          set_has_m9();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(85)) goto parse_m10;
        break;
      }

      // required sfixed32 m10 = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m10:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m10_)));
          set_has_m10();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(93)) goto parse_m11;
        break;
      }

      // required sfixed32 m11 = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m11:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m11_)));
          set_has_m11();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(101)) goto parse_m12;
        break;
      }

      // required sfixed32 m12 = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m12:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m12_)));
          set_has_m12();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(109)) goto parse_m13;
        break;
      }

      // required sfixed32 m13 = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m13:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m13_)));
          set_has_m13();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(117)) goto parse_m14;
        break;
      }

      // required sfixed32 m14 = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m14:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m14_)));
          set_has_m14();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(125)) goto parse_m15;
        break;
      }

      // required sfixed32 m15 = 15;
      case 15: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m15:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m15_)));
          set_has_m15();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(133)) goto parse_m16;
        break;
      }

      // required sfixed32 m16 = 16;
      case 16: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m16:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m16_)));
          set_has_m16();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(141)) goto parse_m17;
        break;
      }

      // required sfixed32 m17 = 17;
      case 17: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m17:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m17_)));
          set_has_m17();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(149)) goto parse_m18;
        break;
      }

      // required sfixed32 m18 = 18;
      case 18: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m18:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m18_)));
          set_has_m18();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(157)) goto parse_m19;
        break;
      }

      // required sfixed32 m19 = 19;
      case 19: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m19:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m19_)));
          set_has_m19();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(165)) goto parse_m20;
        break;
      }

      // required sfixed32 m20 = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m20:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m20_)));
          set_has_m20();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(173)) goto parse_m21;
        break;
      }

      // required sfixed32 m21 = 21;
      case 21: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m21:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m21_)));
          set_has_m21();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(181)) goto parse_m22;
        break;
      }

      // required sfixed32 m22 = 22;
      case 22: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m22:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m22_)));
          set_has_m22();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(189)) goto parse_m23;
        break;
      }

      // required sfixed32 m23 = 23;
      case 23: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m23:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m23_)));
          set_has_m23();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(197)) goto parse_m24;
        break;
      }

      // required sfixed32 m24 = 24;
      case 24: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m24:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m24_)));
          set_has_m24();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(205)) goto parse_m25;
        break;
      }

      // required sfixed32 m25 = 25;
      case 25: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m25:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m25_)));
          set_has_m25();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(213)) goto parse_m26;
        break;
      }

      // required sfixed32 m26 = 26;
      case 26: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m26:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m26_)));
          set_has_m26();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(221)) goto parse_m27;
        break;
      }

      // required sfixed32 m27 = 27;
      case 27: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m27:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m27_)));
          set_has_m27();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(229)) goto parse_m28;
        break;
      }

      // required sfixed32 m28 = 28;
      case 28: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m28:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m28_)));
          set_has_m28();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(237)) goto parse_m29;
        break;
      }

      // required sfixed32 m29 = 29;
      case 29: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m29:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m29_)));
          set_has_m29();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(245)) goto parse_m30;
        break;
      }

      // required sfixed32 m30 = 30;
      case 30: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m30:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m30_)));
          set_has_m30();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(253)) goto parse_m31;
        break;
      }

      // required sfixed32 m31 = 31;
      case 31: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m31:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m31_)));
          set_has_m31();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(261)) goto parse_m32;
        break;
      }

      // required sfixed32 m32 = 32;
      case 32: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m32:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m32_)));
          set_has_m32();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(269)) goto parse_m33;
        break;
      }

      // required sfixed32 m33 = 33;
      case 33: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m33:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m33_)));
          set_has_m33();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(277)) goto parse_m34;
        break;
      }

      // required sfixed32 m34 = 34;
      case 34: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m34:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m34_)));
          set_has_m34();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(285)) goto parse_m35;
        break;
      }

      // required sfixed32 m35 = 35;
      case 35: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m35:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m35_)));
          set_has_m35();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(293)) goto parse_m36;
        break;
      }

      // required sfixed32 m36 = 36;
      case 36: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m36:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m36_)));
          set_has_m36();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(301)) goto parse_m37;
        break;
      }

      // required sfixed32 m37 = 37;
      case 37: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m37:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m37_)));
          set_has_m37();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(309)) goto parse_m38;
        break;
      }

      // required sfixed32 m38 = 38;
      case 38: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m38:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m38_)));
          set_has_m38();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(317)) goto parse_m39;
        break;
      }

      // required sfixed32 m39 = 39;
      case 39: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m39:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m39_)));
          set_has_m39();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(325)) goto parse_m40;
        break;
      }

      // required sfixed32 m40 = 40;
      case 40: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_FIXED32) {
         parse_m40:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>(
                 input, &m40_)));
          set_has_m40();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Performance::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required sfixed32 m1 = 1;
  if (has_m1()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(1, this->m1(), output);
  }

  // required sfixed32 m2 = 2;
  if (has_m2()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(2, this->m2(), output);
  }

  // required sfixed32 m3 = 3;
  if (has_m3()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(3, this->m3(), output);
  }

  // required sfixed32 m4 = 4;
  if (has_m4()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(4, this->m4(), output);
  }

  // required sfixed32 m5 = 5;
  if (has_m5()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(5, this->m5(), output);
  }

  // required sfixed32 m6 = 6;
  if (has_m6()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(6, this->m6(), output);
  }

  // required sfixed32 m7 = 7;
  if (has_m7()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(7, this->m7(), output);
  }

  // required sfixed32 m8 = 8;
  if (has_m8()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(8, this->m8(), output);
  }

  // required sfixed32 m9 = 9;
  if (has_m9()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(9, this->m9(), output);
  }

  // required sfixed32 m10 = 10;
  if (has_m10()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(10, this->m10(), output);
  }

  // required sfixed32 m11 = 11;
  if (has_m11()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(11, this->m11(), output);
  }

  // required sfixed32 m12 = 12;
  if (has_m12()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(12, this->m12(), output);
  }

  // required sfixed32 m13 = 13;
  if (has_m13()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(13, this->m13(), output);
  }

  // required sfixed32 m14 = 14;
  if (has_m14()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(14, this->m14(), output);
  }

  // required sfixed32 m15 = 15;
  if (has_m15()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(15, this->m15(), output);
  }

  // required sfixed32 m16 = 16;
  if (has_m16()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(16, this->m16(), output);
  }

  // required sfixed32 m17 = 17;
  if (has_m17()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(17, this->m17(), output);
  }

  // required sfixed32 m18 = 18;
  if (has_m18()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(18, this->m18(), output);
  }

  // required sfixed32 m19 = 19;
  if (has_m19()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(19, this->m19(), output);
  }

  // required sfixed32 m20 = 20;
  if (has_m20()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(20, this->m20(), output);
  }

  // required sfixed32 m21 = 21;
  if (has_m21()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(21, this->m21(), output);
  }

  // required sfixed32 m22 = 22;
  if (has_m22()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(22, this->m22(), output);
  }

  // required sfixed32 m23 = 23;
  if (has_m23()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(23, this->m23(), output);
  }

  // required sfixed32 m24 = 24;
  if (has_m24()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(24, this->m24(), output);
  }

  // required sfixed32 m25 = 25;
  if (has_m25()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(25, this->m25(), output);
  }

  // required sfixed32 m26 = 26;
  if (has_m26()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(26, this->m26(), output);
  }

  // required sfixed32 m27 = 27;
  if (has_m27()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(27, this->m27(), output);
  }

  // required sfixed32 m28 = 28;
  if (has_m28()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(28, this->m28(), output);
  }

  // required sfixed32 m29 = 29;
  if (has_m29()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(29, this->m29(), output);
  }

  // required sfixed32 m30 = 30;
  if (has_m30()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(30, this->m30(), output);
  }

  // required sfixed32 m31 = 31;
  if (has_m31()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(31, this->m31(), output);
  }

  // required sfixed32 m32 = 32;
  if (has_m32()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(32, this->m32(), output);
  }

  // required sfixed32 m33 = 33;
  if (has_m33()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(33, this->m33(), output);
  }

  // required sfixed32 m34 = 34;
  if (has_m34()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(34, this->m34(), output);
  }

  // required sfixed32 m35 = 35;
  if (has_m35()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(35, this->m35(), output);
  }

  // required sfixed32 m36 = 36;
  if (has_m36()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(36, this->m36(), output);
  }

  // required sfixed32 m37 = 37;
  if (has_m37()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(37, this->m37(), output);
  }

  // required sfixed32 m38 = 38;
  if (has_m38()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(38, this->m38(), output);
  }

  // required sfixed32 m39 = 39;
  if (has_m39()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(39, this->m39(), output);
  }

  // required sfixed32 m40 = 40;
  if (has_m40()) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed32(40, this->m40(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Performance::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required sfixed32 m1 = 1;
  if (has_m1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(1, this->m1(), target);
  }

  // required sfixed32 m2 = 2;
  if (has_m2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(2, this->m2(), target);
  }

  // required sfixed32 m3 = 3;
  if (has_m3()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(3, this->m3(), target);
  }

  // required sfixed32 m4 = 4;
  if (has_m4()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(4, this->m4(), target);
  }

  // required sfixed32 m5 = 5;
  if (has_m5()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(5, this->m5(), target);
  }

  // required sfixed32 m6 = 6;
  if (has_m6()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(6, this->m6(), target);
  }

  // required sfixed32 m7 = 7;
  if (has_m7()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(7, this->m7(), target);
  }

  // required sfixed32 m8 = 8;
  if (has_m8()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(8, this->m8(), target);
  }

  // required sfixed32 m9 = 9;
  if (has_m9()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(9, this->m9(), target);
  }

  // required sfixed32 m10 = 10;
  if (has_m10()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(10, this->m10(), target);
  }

  // required sfixed32 m11 = 11;
  if (has_m11()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(11, this->m11(), target);
  }

  // required sfixed32 m12 = 12;
  if (has_m12()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(12, this->m12(), target);
  }

  // required sfixed32 m13 = 13;
  if (has_m13()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(13, this->m13(), target);
  }

  // required sfixed32 m14 = 14;
  if (has_m14()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(14, this->m14(), target);
  }

  // required sfixed32 m15 = 15;
  if (has_m15()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(15, this->m15(), target);
  }

  // required sfixed32 m16 = 16;
  if (has_m16()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(16, this->m16(), target);
  }

  // required sfixed32 m17 = 17;
  if (has_m17()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(17, this->m17(), target);
  }

  // required sfixed32 m18 = 18;
  if (has_m18()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(18, this->m18(), target);
  }

  // required sfixed32 m19 = 19;
  if (has_m19()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(19, this->m19(), target);
  }

  // required sfixed32 m20 = 20;
  if (has_m20()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(20, this->m20(), target);
  }

  // required sfixed32 m21 = 21;
  if (has_m21()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(21, this->m21(), target);
  }

  // required sfixed32 m22 = 22;
  if (has_m22()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(22, this->m22(), target);
  }

  // required sfixed32 m23 = 23;
  if (has_m23()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(23, this->m23(), target);
  }

  // required sfixed32 m24 = 24;
  if (has_m24()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(24, this->m24(), target);
  }

  // required sfixed32 m25 = 25;
  if (has_m25()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(25, this->m25(), target);
  }

  // required sfixed32 m26 = 26;
  if (has_m26()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(26, this->m26(), target);
  }

  // required sfixed32 m27 = 27;
  if (has_m27()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(27, this->m27(), target);
  }

  // required sfixed32 m28 = 28;
  if (has_m28()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(28, this->m28(), target);
  }

  // required sfixed32 m29 = 29;
  if (has_m29()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(29, this->m29(), target);
  }

  // required sfixed32 m30 = 30;
  if (has_m30()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(30, this->m30(), target);
  }

  // required sfixed32 m31 = 31;
  if (has_m31()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(31, this->m31(), target);
  }

  // required sfixed32 m32 = 32;
  if (has_m32()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(32, this->m32(), target);
  }

  // required sfixed32 m33 = 33;
  if (has_m33()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(33, this->m33(), target);
  }

  // required sfixed32 m34 = 34;
  if (has_m34()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(34, this->m34(), target);
  }

  // required sfixed32 m35 = 35;
  if (has_m35()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(35, this->m35(), target);
  }

  // required sfixed32 m36 = 36;
  if (has_m36()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(36, this->m36(), target);
  }

  // required sfixed32 m37 = 37;
  if (has_m37()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(37, this->m37(), target);
  }

  // required sfixed32 m38 = 38;
  if (has_m38()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(38, this->m38(), target);
  }

  // required sfixed32 m39 = 39;
  if (has_m39()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(39, this->m39(), target);
  }

  // required sfixed32 m40 = 40;
  if (has_m40()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed32ToArray(40, this->m40(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Performance::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required sfixed32 m1 = 1;
    if (has_m1()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m2 = 2;
    if (has_m2()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m3 = 3;
    if (has_m3()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m4 = 4;
    if (has_m4()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m5 = 5;
    if (has_m5()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m6 = 6;
    if (has_m6()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m7 = 7;
    if (has_m7()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m8 = 8;
    if (has_m8()) {
      total_size += 1 + 4;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required sfixed32 m9 = 9;
    if (has_m9()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m10 = 10;
    if (has_m10()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m11 = 11;
    if (has_m11()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m12 = 12;
    if (has_m12()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m13 = 13;
    if (has_m13()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m14 = 14;
    if (has_m14()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m15 = 15;
    if (has_m15()) {
      total_size += 1 + 4;
    }

    // required sfixed32 m16 = 16;
    if (has_m16()) {
      total_size += 2 + 4;
    }

  }
  if (_has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    // required sfixed32 m17 = 17;
    if (has_m17()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m18 = 18;
    if (has_m18()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m19 = 19;
    if (has_m19()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m20 = 20;
    if (has_m20()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m21 = 21;
    if (has_m21()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m22 = 22;
    if (has_m22()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m23 = 23;
    if (has_m23()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m24 = 24;
    if (has_m24()) {
      total_size += 2 + 4;
    }

  }
  if (_has_bits_[24 / 32] & (0xffu << (24 % 32))) {
    // required sfixed32 m25 = 25;
    if (has_m25()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m26 = 26;
    if (has_m26()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m27 = 27;
    if (has_m27()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m28 = 28;
    if (has_m28()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m29 = 29;
    if (has_m29()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m30 = 30;
    if (has_m30()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m31 = 31;
    if (has_m31()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m32 = 32;
    if (has_m32()) {
      total_size += 2 + 4;
    }

  }
  if (_has_bits_[32 / 32] & (0xffu << (32 % 32))) {
    // required sfixed32 m33 = 33;
    if (has_m33()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m34 = 34;
    if (has_m34()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m35 = 35;
    if (has_m35()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m36 = 36;
    if (has_m36()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m37 = 37;
    if (has_m37()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m38 = 38;
    if (has_m38()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m39 = 39;
    if (has_m39()) {
      total_size += 2 + 4;
    }

    // required sfixed32 m40 = 40;
    if (has_m40()) {
      total_size += 2 + 4;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Performance::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Performance* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Performance*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Performance::MergeFrom(const Performance& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_m1()) {
      set_m1(from.m1());
    }
    if (from.has_m2()) {
      set_m2(from.m2());
    }
    if (from.has_m3()) {
      set_m3(from.m3());
    }
    if (from.has_m4()) {
      set_m4(from.m4());
    }
    if (from.has_m5()) {
      set_m5(from.m5());
    }
    if (from.has_m6()) {
      set_m6(from.m6());
    }
    if (from.has_m7()) {
      set_m7(from.m7());
    }
    if (from.has_m8()) {
      set_m8(from.m8());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_m9()) {
      set_m9(from.m9());
    }
    if (from.has_m10()) {
      set_m10(from.m10());
    }
    if (from.has_m11()) {
      set_m11(from.m11());
    }
    if (from.has_m12()) {
      set_m12(from.m12());
    }
    if (from.has_m13()) {
      set_m13(from.m13());
    }
    if (from.has_m14()) {
      set_m14(from.m14());
    }
    if (from.has_m15()) {
      set_m15(from.m15());
    }
    if (from.has_m16()) {
      set_m16(from.m16());
    }
  }
  if (from._has_bits_[16 / 32] & (0xffu << (16 % 32))) {
    if (from.has_m17()) {
      set_m17(from.m17());
    }
    if (from.has_m18()) {
      set_m18(from.m18());
    }
    if (from.has_m19()) {
      set_m19(from.m19());
    }
    if (from.has_m20()) {
      set_m20(from.m20());
    }
    if (from.has_m21()) {
      set_m21(from.m21());
    }
    if (from.has_m22()) {
      set_m22(from.m22());
    }
    if (from.has_m23()) {
      set_m23(from.m23());
    }
    if (from.has_m24()) {
      set_m24(from.m24());
    }
  }
  if (from._has_bits_[24 / 32] & (0xffu << (24 % 32))) {
    if (from.has_m25()) {
      set_m25(from.m25());
    }
    if (from.has_m26()) {
      set_m26(from.m26());
    }
    if (from.has_m27()) {
      set_m27(from.m27());
    }
    if (from.has_m28()) {
      set_m28(from.m28());
    }
    if (from.has_m29()) {
      set_m29(from.m29());
    }
    if (from.has_m30()) {
      set_m30(from.m30());
    }
    if (from.has_m31()) {
      set_m31(from.m31());
    }
    if (from.has_m32()) {
      set_m32(from.m32());
    }
  }
  if (from._has_bits_[32 / 32] & (0xffu << (32 % 32))) {
    if (from.has_m33()) {
      set_m33(from.m33());
    }
    if (from.has_m34()) {
      set_m34(from.m34());
    }
    if (from.has_m35()) {
      set_m35(from.m35());
    }
    if (from.has_m36()) {
      set_m36(from.m36());
    }
    if (from.has_m37()) {
      set_m37(from.m37());
    }
    if (from.has_m38()) {
      set_m38(from.m38());
    }
    if (from.has_m39()) {
      set_m39(from.m39());
    }
    if (from.has_m40()) {
      set_m40(from.m40());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Performance::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Performance::CopyFrom(const Performance& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Performance::IsInitialized() const {
  if ((_has_bits_[0] & 0xffffffff) != 0xffffffff) return false;
  if ((_has_bits_[1] & 0x000000ff) != 0x000000ff) return false;

  return true;
}

void Performance::Swap(Performance* other) {
  if (other != this) {
    std::swap(m1_, other->m1_);
    std::swap(m2_, other->m2_);
    std::swap(m3_, other->m3_);
    std::swap(m4_, other->m4_);
    std::swap(m5_, other->m5_);
    std::swap(m6_, other->m6_);
    std::swap(m7_, other->m7_);
    std::swap(m8_, other->m8_);
    std::swap(m9_, other->m9_);
    std::swap(m10_, other->m10_);
    std::swap(m11_, other->m11_);
    std::swap(m12_, other->m12_);
    std::swap(m13_, other->m13_);
    std::swap(m14_, other->m14_);
    std::swap(m15_, other->m15_);
    std::swap(m16_, other->m16_);
    std::swap(m17_, other->m17_);
    std::swap(m18_, other->m18_);
    std::swap(m19_, other->m19_);
    std::swap(m20_, other->m20_);
    std::swap(m21_, other->m21_);
    std::swap(m22_, other->m22_);
    std::swap(m23_, other->m23_);
    std::swap(m24_, other->m24_);
    std::swap(m25_, other->m25_);
    std::swap(m26_, other->m26_);
    std::swap(m27_, other->m27_);
    std::swap(m28_, other->m28_);
    std::swap(m29_, other->m29_);
    std::swap(m30_, other->m30_);
    std::swap(m31_, other->m31_);
    std::swap(m32_, other->m32_);
    std::swap(m33_, other->m33_);
    std::swap(m34_, other->m34_);
    std::swap(m35_, other->m35_);
    std::swap(m36_, other->m36_);
    std::swap(m37_, other->m37_);
    std::swap(m38_, other->m38_);
    std::swap(m39_, other->m39_);
    std::swap(m40_, other->m40_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_has_bits_[1], other->_has_bits_[1]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Performance::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Performance_descriptor_;
  metadata.reflection = Performance_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace performance

// @@protoc_insertion_point(global_scope)
